spring:
  profiles:
    active: dev
quiz:
  questions:
    default:
    - prompt: "Which keyword is used to declare a variable in Java?"
      choices:
        A: "let"
        B: "variable"
        C: "const"
        D: "int"

    - prompt: "What is the difference between a class and an object in Java?"
      choices:
        A: "A class is a collection of objects, while an object is an instance of a class."
        B: "A class is used for inheritance, while an object is used for polymorphism."
        C: "A class is a blueprint for creating objects, while an object is a collection of classes."
        D: "A class is a data type, while an object is a method."

    - prompt: "Which data type is used to store whole numbers in Java?"
      choices:
        A: "boolean"
        B: "String"
        C: "double"
        D: "long"

    - prompt: "What is the correct syntax for declaring a string variable in Java?"
      choices:
        A: "String name = \"John\";"
        B: "string name = 'John';"
        C: "String name = 'John';"
        D: "string name = \"John\";"

    - prompt: "What is the purpose of the 'if' statement in Java?"
      choices:
        A: "To repeat a block of code a specific number of times."
        B: "To execute a block of code only if a certain condition is true."
        C: "To define a method in a class."
        D: "To declare a variable."

    - prompt: "Which operator is used to compare two values for equality in Java?"
      choices:
        A: "!="
        B: ">"
        C: "=="
        D: "="

    - prompt: "What is the purpose of the 'for' loop in Java?"
      choices:
        A: "To execute a block of code only if a certain condition is true."
        B: "To repeat a block of code a specific number of times."
        C: "To define a method in a class."
        D: "To declare a variable."

    - prompt: "Which data type is used to store decimal numbers in Java?"
      choices:
        A: "boolean"
        B: "String"
        C: "int"
        D: "double"

    - prompt: "What is the purpose of the 'while' loop in Java?"
      choices:
        A: "To execute a block of code only if a certain condition is true."
        B: "To define a method in a class."
        C: "To repeat a block of code as long as a certain condition is true."
        D: "To declare a variable."

    - prompt: "What is the purpose of the 'switch' statement in Java?"
      choices:
        A: "To repeat a block of code a specific number of times."
        B: "To declare a variable."
        C: "To define a method in a class."
        D: "To select one of many code blocks to be executed."

    - prompt: "Which data type is used to store true or false values in Java?"
      choices:
        A: "int"
        B: "double"
        C: "String"
        D: "boolean"

    - prompt: "What is the correct syntax for declaring an integer variable in Java?"
      choices:
        A: "integer num = '10';"
        B: "int num = 10;"
        C: "integer num = 10;"
        D: "int num = '10';"

    - prompt: "What is the purpose of the 'else' statement in Java?"
      choices:
        A: "To repeat a block of code a specific number of times."
        B: "To declare a variable."
        C: "To define a method in a class."
        D: "To execute a block of code if the 'if' condition is false."

    - prompt: "Which data type is used to store text in Java?"
      choices:
        A: "String"
        B: "int"
        C: "double"
        D: "boolean"

    - prompt: "What is the correct syntax for declaring a double variable in Java?"
      choices:
        A: "double num = '3.14';"
        B: "double num = 3,14;"
        C: "double num = \"3.14\";"
        D: "double num = 3.14;"

    - prompt: "What is encapsulation in object-oriented programming?"
      choices:
        A: "Encapsulation is the process of creating multiple instances of a class."
        B: "Encapsulation is the process of defining a class."
        C: "Encapsulation is the process of hiding internal data and methods of an object and providing access to it only through public methods."
        D: "Encapsulation is the process of inheriting properties and behaviors from a parent class."

    - prompt: "What is inheritance in object-oriented programming?"
      choices:
        A: "Inheritance is the process of creating multiple instances of a class."
        B: "Inheritance is the process of defining a class."
        C: "Inheritance is the process of hiding internal data and methods of an object and providing access to it only through public methods."
        D: "Inheritance is the process of inheriting properties and behaviors from a parent class."

    - prompt: "What is polymorphism in object-oriented programming?"
      choices:
        A: "Polymorphism is the process of creating multiple instances of a class."
        B: "Polymorphism is the process of defining a class."
        C: "Polymorphism is the process of hiding internal data and methods of an object and providing access to it only through public methods."
        D: "Polymorphism is the process of using a single interface to represent different types of objects."

    - prompt: "What is abstraction in object-oriented programming?"
      choices:
        A: "Abstraction is the process of creating multiple instances of a class."
        B: "Abstraction is the process of simplifying complex systems by breaking them down into smaller, more manageable parts."
        C: "Abstraction is the process of defining a class."
        D: "Abstraction is the process of hiding internal data and methods of an object and providing access to it only through public methods."

    - prompt: "Which principle of object-oriented programming allows objects of different classes to be treated as objects of the same class?"
      choices:
        A: "Inheritance"
        B: "Polymorphism"
        C: "Encapsulation"
        D: "Abstraction"

    - prompt: "What is the naming convention for classes in Java?"
      choices:
        A: "camelCase"
        B: "PascalCase"
        C: "snake_case"
        D: "kebab-case"

    - prompt: "What is the naming convention for variables in Java?"
      choices:
        A: "PascalCase"
        B: "camelCase"
        C: "snake_case"
        D: "kebab-case"

    - prompt: "What is the naming convention for methods in Java?"
      choices:
        A: "PascalCase"
        B: "snake_case"
        C: "kebab-case"
        D: "camelCase"

    - prompt: "What is the naming convention for packages in Java?"
      choices:
        A: "PascalCase"
        B: "snake_case"
        C: "lowercase"
        D: "kebab-case"

    - prompt: "What is Git?"
      choices:
        A: "A programming language commonly used for web development."
        B: "A version control system used for tracking changes in files and coordinating work among multiple people."
        C: "A database management system for storing and retrieving data."
        D: "A software development methodology for agile project management."

    - prompt: "What is a commit in Git?"
      choices:
        A: "A software tool used for analyzing and optimizing code."
        B: "A command used to merge branches in Git."
        C: "A record of changes made to a repository at a specific point in time."
        D: "A file that contains the source code of a program."

    - prompt: "What is a branch in Git?"
      choices:
        A: "A command used to create a new repository in Git."
        B: "A separate line of development that allows you to work on a feature or bug fix without affecting the main codebase."
        C: "A file that contains the configuration settings for a program."
        D: "A software tool used for managing dependencies in a project."

    - prompt: "What is a merge conflict in Git?"
      choices:
        A: "A command used to discard changes and revert to a previous version in Git."
        B: "A file that contains the documentation and instructions for using a program."
        C: "A situation that occurs when Git is unable to automatically merge changes from different branches."
        D: "A software tool used for profiling and optimizing code performance."

    - prompt: "What command should you use to restore a file to its state at an earlier commit?"
      choices:
        A: "git reset <commit-hash> <file>"
        B: "git checkout <commit-hash> <file>"
        C: "git restore <commit-hash> <file>"
        D: "git revert <commit-hash> <file>"

    - prompt: "What Git command do you use to create a new branch?"
      choices:
        A: "git checkout -b <branch-name>"
        B: "git branch <branch-name>"
        C: "git commit -m 'Create branch'"
        D: "git merge <branch-name>"
  answers:
    default:
      - $2y$10$mhwamqUPf8AlI2N9UNSOve/PNRo1aKKRXGVVyuAZmXTByDKjE7Htm
      - $2y$10$VHv7.t7MLdDE8Fd2Hqo.oOhH0VUfu6jT2aZRPaeWypmZb9YYTjOQK
      - $2y$10$XKYYo.Kqr3OH9taIQ3ktWeby29gt1EWQqI652O3Olim5thHd7MmDm
      - $2y$10$KfuFshyYl.EMU8/R6UgZeOTjgRctSejlttkAaQxRLw7bcriMbC/BO
      - $2y$10$IjYrvmc.kHlQl1RgOx5czOZBSWIt17PDhbzqQ4y34wBVKUOv7ndM6
      - $2y$10$I3iiNwXF8a1/NlhonKKhKeykCUKF8JbfYmfSe/Fnm9BFyyvxJWTYK
      - $2y$10$AoEJX6ZNU3M/drohEN9FQ.TGDM/sCCyaRLVIquzZ9aBpF0nGbXY5q
      - $2y$10$2XgmrcrXQhdIEVg4VG2kmOJ7q4SsQ5m7ADBP7OoTrYzHdd.zVsVYe
      - $2y$10$xDqH8PMa29gEBZLyzSNwH.zVjsMlSw0S9xKP4hirXpCUkGPpV4OCO
      - $2y$10$/bYGhp..VtYS.WLkUxl0CeKCPfxazFib.dIDKffpZHn9vcRRMIYXe
      - $2y$10$iDtgVSWSR.pT2e3RIIkWq./.wr.rd8OEyRyE.L5.hjPXzHknlU1w2
      - $2y$10$3X1snpG9.yaWfCIJvO60W.EiKjsNYPC1y6h6DjI.4t.sy1TYh5WqG
      - $2y$10$.eRBNLeZnI7/gcrlvKjbK.MqBvcMAng7Xwb5meNoA2psW4osaWTSq
      - $2y$10$BVgsKcyAupOvIs3PENI8VuXDpcLT79WCvAKCL3lasIko1xOySVCba
      - $2y$10$cQaUh8BtUxyA.Uy4I6fTV.jy9pvOQlUlWJCXkmdA/hXFSe.hXkneu
      - $2y$10$cbSbw.rKDqRcKpEjzxWLHeGZ05b/UeIlRwpQAiFgaJmyPHJ.ruCt6
      - $2y$10$eeKtu6LJx7qsFO/DqH/TQ.6loAKI6tJjgXQtqjxazA3z.NKQeyTku
      - $2y$10$YG066HQb9BwlOzi2vcRpKeSDShaeE8SPlOzhAtPMVhvCYEW6qS4q2
      - $2y$10$LME4LyliAhiVxD6BtkzsQuLuG5zLjydoarE9r2dSw.3Nb6aGWT.fC
      - $2y$10$IL3165Mie6PPSdQ61keHm.e7t1lzFH5RZOkq5kFwrKNJBLAOPi89u
      - $2y$10$5xUEwhWf.47OVHhP1ForuuFKqFto0ZGAnZNpe7DS1dhw3Imq91qye
      - $2y$10$G0l0E4QQQkAupN92Y.2hTetAhIeq1C0hOhDUZvE/Vb3rTsvWqBUIO
      - $2y$10$9h4YJXOcBYFUTg5SbWvWG.OpNOAIREXYd0zUCsojizdoFr0dkpK9C
      - $2y$10$9jCWir.loewv48CkBGTpKOF5BdffKHET7134v1eXRxI.BI6JAiwtK
      - $2y$10$TVAUHe1Qnfp9HBrLKaXoaeOcgogKCOh75Xl0g4slyGE59q2OuzLIW
      - $2y$10$IbU1hFYURn2c/3n3vU1EiulH/J7RiYbRJZqntaJuFeF5SiYiK87ju
      - $2y$10$Tn7OfgalNswMFsDDYqg0se65LbgDIitoI5r/.NqrbGlbWnG0wZAh.
      - $2y$10$N6tLPnI/ME0fct9ELNNqNe5gHye3mtBh7LHfduIhsPEELSAROvBri
      - $2y$10$k2Pb2AIjqMcPBxhauVo2fuRNuzQnje7w/wTs6vhf2X/jKdYSWBkJa
      - $2y$10$ccOFeGlKvjS24vEbry0jT.LWTGdQ5Z641XCf2FSPTuF7x9PN4RJw6
