spring:
  profiles:
    active: dev
quiz:
  questions:
    default:
    - prompt: "Which keyword is used to declare a variable in Java?"
      choices:
        A: "const"
        B: "let"
        C: "int"
        D: "variable"

    - prompt: "What is the difference between a class and an object in Java?"
      choices:
        A: "A class is a blueprint for creating objects, while an object is an instance of a class."
        B: "A class is a collection of objects, while an object is a collection of classes."
        C: "A class is used for inheritance, while an object is used for polymorphism."
        D: "A class is a data type, while an object is a method."

    - prompt: "Which data type is used to store whole numbers in Java?"
      choices:
        A: "int"
        B: "double"
        C: "boolean"
        D: "String"

    - prompt: "What is the correct syntax for declaring a string variable in Java?"
      choices:
        A: "String name = 'John';"
        B: "String name = \"John\";"
        C: "string name = 'John';"
        D: "string name = \"John\";"

    - prompt: "What is the purpose of the 'if' statement in Java?"
      choices:
        A: "To execute a block of code only if a certain condition is true."
        B: "To repeat a block of code a specific number of times."
        C: "To define a method in a class."
        D: "To declare a variable."

    - prompt: "Which operator is used to compare two values for equality in Java?"
      choices:
        A: "=="
        B: "!="
        C: "<"
        D: ">"

    - prompt: "What is the purpose of the 'for' loop in Java?"
      choices:
        A: "To repeat a block of code a specific number of times."
        B: "To execute a block of code only if a certain condition is true."
        C: "To define a method in a class."
        D: "To declare a variable."

    - prompt: "Which data type is used to store decimal numbers in Java?"
      choices:
        A: "double"
        B: "int"
        C: "boolean"
        D: "String"

    - prompt: "What is the purpose of the 'while' loop in Java?"
      choices:
        A: "To repeat a block of code as long as a certain condition is true."
        B: "To execute a block of code only if a certain condition is true."
        C: "To define a method in a class."
        D: "To declare a variable."

    - prompt: "What is the purpose of the 'switch' statement in Java?"
      choices:
        A: "To select one of many code blocks to be executed."
        B: "To repeat a block of code a specific number of times."
        C: "To define a method in a class."
        D: "To declare a variable."

    - prompt: "Which data type is used to store true or false values in Java?"
      choices:
        A: "boolean"
        B: "int"
        C: "double"
        D: "String"

    - prompt: "What is the correct syntax for declaring an integer variable in Java?"
      choices:
        A: "int num = 10;"
        B: "integer num = 10;"
        C: "int num = '10';"
        D: "integer num = '10';"

    - prompt: "What is the purpose of the 'else' statement in Java?"
      choices:
        A: "To execute a block of code if the 'if' condition is false."
        B: "To repeat a block of code a specific number of times."
        C: "To define a method in a class."
        D: "To declare a variable."

    - prompt: "Which data type is used to store text in Java?"
      choices:
        A: "String"
        B: "int"
        C: "boolean"
        D: "double"

    - prompt: "What is the correct syntax for declaring a double variable in Java?"
      choices:
        A: "double num = 3.14;"
        B: "double num = '3.14';"
        C: "double num = \"3.14\";"
        D: "double num = 3,14;"

    - prompt: "What is encapsulation in object-oriented programming?"
      choices:
        A: "Encapsulation is the process of hiding internal data and methods of an object and providing access to it only through public methods."
        B: "Encapsulation is the process of creating multiple instances of a class."
        C: "Encapsulation is the process of defining a class."
        D: "Encapsulation is the process of inheriting properties and behaviors from a parent class."

    - prompt: "What is inheritance in object-oriented programming?"
      choices:
        A: "Inheritance is the process of creating multiple instances of a class."
        B: "Inheritance is the process of defining a class."
        C: "Inheritance is the process of hiding internal data and methods of an object and providing access to it only through public methods."
        D: "Inheritance is the process of inheriting properties and behaviors from a parent class."

    - prompt: "What is polymorphism in object-oriented programming?"
      choices:
        A: "Polymorphism is the process of creating multiple instances of a class."
        B: "Polymorphism is the process of defining a class."
        C: "Polymorphism is the process of hiding internal data and methods of an object and providing access to it only through public methods."
        D: "Polymorphism is the process of using a single interface to represent different types of objects."

    - prompt: "What is abstraction in object-oriented programming?"
      choices:
        A: "Abstraction is the process of creating multiple instances of a class."
        B: "Abstraction is the process of defining a class."
        C: "Abstraction is the process of hiding internal data and methods of an object and providing access to it only through public methods."
        D: "Abstraction is the process of simplifying complex systems by breaking them down into smaller, more manageable parts."

    - prompt: "Which principle of object-oriented programming allows objects of different classes to be treated as objects of the same class?"
      choices:
        A: "Encapsulation"
        B: "Inheritance"
        C: "Polymorphism"
        D: "Abstraction"

    - prompt: "What is the naming convention for classes in Java?"
      choices:
        A: "PascalCase"
        B: "camelCase"
        C: "snake_case"
        D: "kebab-case"

    - prompt: "What is the naming convention for variables in Java?"
      choices:
        A: "camelCase"
        B: "PascalCase"
        C: "snake_case"
        D: "kebab-case"

    - prompt: "What is the naming convention for constants in Java?"
      choices:
        A: "UPPER_CASE"
        B: "camelCase"
        C: "snake_case"
        D: "kebab-case"

    - prompt: "What is the naming convention for methods in Java?"
      choices:
        A: "camelCase"
        B: "PascalCase"
        C: "snake_case"
        D: "kebab-case"

    - prompt: "What is the naming convention for packages in Java?"
      choices:
        A: "lowercase"
        B: "PascalCase"
        C: "snake_case"
        D: "kebab-case"

    - prompt: "What is Git?"
      choices:
        A: "A version control system used for tracking changes in files and coordinating work among multiple people."
        B: "A programming language commonly used for web development."
        C: "A database management system for storing and retrieving data."
        D: "A software development methodology for agile project management."

    - prompt: "What is a repository in Git?"
      choices:
        A: "A collection of files and folders that stores the history of changes made to them."
        B: "A programming construct used for storing and manipulating data."
        C: "A server that hosts the Git version control system."
        D: "A software tool used for debugging and testing code."

    - prompt: "What is a commit in Git?"
      choices:
        A: "A record of changes made to a repository at a specific point in time."
        B: "A command used to merge branches in Git."
        C: "A file that contains the source code of a program."
        D: "A software tool used for analyzing and optimizing code."

    - prompt: "What is a branch in Git?"
      choices:
        A: "A separate line of development that allows you to work on a feature or bug fix without affecting the main codebase."
        B: "A command used to create a new repository in Git."
        C: "A file that contains the configuration settings for a program."
        D: "A software tool used for managing dependencies in a project."

    - prompt: "What is a merge conflict in Git?"
      choices:
        A: "A situation that occurs when Git is unable to automatically merge changes from different branches."
        B: "A command used to discard changes and revert to a previous version in Git."
        C: "A file that contains the documentation and instructions for using a program."
        D: "A software tool used for profiling and optimizing code performance."

    - prompt: "What command should you use to restore a file to its state at an earlier commit"
      choices:
        A: "git checkout <commit-hash> <file>"
        B: "git reset <commit-hash> <file>"
        C: "git revert <commit-hash> <file>"
        D: "git restore <commit-hash> <file>"

    - prompt: "What Git command do you use to create a new branch?"
      choices:
        A: "git branch <branch-name>"
        B: "git checkout -b <branch-name>"
        C: "git commit -m 'Create branch'"
        D: "git merge <branch-name>"